### ISSUE TITLE
Apollo - Automatic persisted queries

### ISSUE THREAD

**Issue by Trobyss** [nicholasaleks/graphql-threat-matrix#3]
Hi !

I think there is a mistake with apollo: its supports automatic persisted queries 

=> https://www.apollographql.com/docs/apollo-server/performance/apq/

Trobyss

edit: https://github.com/nicholasaleks/graphql-threat-matrix/pull/4

**Comment by dolevf** [comment]
Addressed, Thank you @Trobyss !
